### ISSUE TITLE
咋个使用的，感觉nsis比inno要复杂

### ISSUE THREAD

**Issue by bajins** [kingsunc/Nsis_Duilib#1]

**Comment by kingsunc** [comment]
运行 build_install.bat output里有输出setup.exe，打包文件放在FilesToInstall文件夹内，自定义的自己修改安装脚本就行

**Comment by bajins** [comment]
> 运行 build_install.bat output里有输出setup.exe，打包文件放在FilesToInstall文件夹内，自定义的自己修改安装脚本就行

请问有UI修改的详细说明吗？就像我修改的这个项目 https://github.com/woytu/NSIS_SetupSkin

**Comment by bajins** [comment]
请问这个是Duilib的标准目录结构吗？怎么跟牛牛控件那个相似呢？

**Comment by bajins** [comment]
> 请问这个是Duilib的标准目录结构吗？怎么跟牛牛控件那个相似呢？

哦，我已经看到了牛牛界面控件的插件
